### ISSUE TITLE
Ranking function?

### ISSUE THREAD

**Issue by daegontaven** [philihp/openskill.js#111]
There seems to be no `rank()` function as described in the README. Is this because it hasn't been implemented yet?

**Comment by philihp** [comment]
Hi! I hope this finds you well.

This isn't implemented yet; currently if you sort the order of your teams before sending them in, it should work.

If you wanna score games/matches with ties (e.g. two teams in first, one team in third), there's no way to express this without that, and it's something I wanted to do once I was trying to score a game with ties. Apologies :) It's for sure something that's coming.

**Comment by brezinajn** [comment]
This is something I would be interested in as well. Great work btw @philihp!

**Comment by philihp** [comment]
Support for rank has been added in `v1.1.0`. It doesn't do anything special for ties, yet (although it doesn't blow up if you have them). More to come soon :smile:

**Comment by philihp** [comment]
Support for ties should be available in version `v1.2.0`

I would love to hear about how you're using this, if you're able to share.

**Comment by daegontaven** [comment]
I was planning on using it to rate debates using a bot on discord. We are currently using a multiplayer version of ELO to score.

**Comment by brezinajn** [comment]
> I would love to hear about how you're using this, if you're able to share.

We have in-company table footbal leaderboards (no ties there) and we would like to extend the app to be more general and usable for any competition. Additionally I have a wrapper around a game server paired with a Discord bot. Effectively creating semi-private league without a support from the game :)
