### ISSUE TITLE
Plackett-Luce vs Bradley-Terry Full Pairs

### ISSUE THREAD

**Issue by luiscastro193** [philihp/openskill.js#112]
Thanks a lot for the library, it seems super useful for matchmaking. I just have one question.

The Plackett-Luce model is the default model over the Bradley-Terry Full Pairs. Why? In which situations is one preferred over the other?

**Comment by luiscastro193** [comment]
They seem equivalent for Team vs Team situations so I will stick to Bradley-Terry Full Pairs since it is faster. I'm still curious about the difference though.

**Comment by philihp** [comment]
You're most welcome! Plackett-Luce is a generalized form of Bradley-Terry full pairing. For only two teams you're correct, and they're equivalent. This is really where TrueSkill starts to struggle on the CPU side of things and just approximate results via message passing in a factor graph.

**Comment by luiscastro193** [comment]
Oh I see, good to know. This can be closed then.
