### ISSUE TITLE
Make Typescript a thing

### ISSUE THREAD

**Issue by philihp** [philihp/openskill.js#202]
* This task entails renaming relevant files from `.js` to `.ts`
* Add the necessary dependencies
* Ensure that the library still compiles as expected. This should not be a breaking feature.

**Comment by SwapnilSoni1999** [comment]
How about adding a `index.d.ts` file?

**Comment by philihp** [comment]
If such a thing is a well-typed file, I would accept that. Don't just give every output the type `any` 😉

**Comment by SwapnilSoni1999** [comment]
> If such a thing is a well-typed file, I would accept that. Don't just give every output the type `any` wink

Yep I wont, If possible then I'll surely try to convert it to ts first

**Comment by brezinajn** [comment]
👍 Typing the code would greatly help with porting to other platforms :). Currently I'm implementing the tied matches feature in the Kotlin port and the lack of types doesn't help at all :D

**Comment by philihp** [comment]
@SwapnilSoni1999 if you are still working on this, please put up a draft PR.
