### ISSUE TITLE
Which model to use?

### ISSUE THREAD

**Issue by slice3984** [philihp/openskill.js#208]
I'm using the trueskill js port for my bot which is used to organize games at the moment. Since there is no way to take team scores into account for ratings I wanted to use openskill.js instead. Since the library offers different models I wanted to ask which model suits my requirements the best. Players in a team can range from one to ten and there can be up to ten teams.

**Comment by slice3984** [comment]
Just noticed providing scores in openskill just translates to rankings, is there a way to take actual game team scores into the rating that also influence them based on how close the teams got to each other?

**Comment by philihp** [comment]
Hi!

Any of the models should be fine, feel free to try them all. With full-pairing models, the runtime increases exponentially with the number of teams, however if you only have 10 teams this never runs away. Bradley Terry uses logistic distribution curve, while Thurston Mosteller uses gaussian. If you think you might have to re-run your ratings in different languages, you might have better portability with Bradley Terry. Gaussian curves can have slightly different implementations across system.

There isn't natively a way to take scores into account for a match. While useful, you can still get a pretty good rating after only a couple dozen matches. If that's not satisfying, perhaps treat treat every point scored as a match. This could also be useful if your active team has a lot of players tagging in and out, as in most team sports. I'd love to see the two approaches benchmarked against each other to see if there's a statistically significant meaningful lift in how well you can predict outcome with these ratings.

**Comment by slice3984** [comment]
Thanks for your response,
treating every round as it's own game sounds like it would cause problems in the variance dropping too fast over time. Cost of computation also increases significantly especially when there is the need to rerate multiple games when there's a need to update the outcome / score of a previous match. Is using the score as weights a viable solution? Close game scores result in a low weight, team scores far apart result in a high weight. To be honest I don't really know much about how the rating systems work and just searched for some easy solution of how to take team scores into account. Maybe just using wins / losses without additional input is still the best solution.

**Comment by philihp** [comment]
I don't know of any rating systems which use score or margin/spread of the win. Score requires a lot of context of the game. In basketball, if one team leads the other by 10 points the entire game, and wins with a score of 100-110, is that a close game? It's a 10% difference. Meanwhile in hockey, a team have a very close win of 1-2, getting the last point in the very end. It's a 50% difference, but that would have been a close game.

That isn't to say that we can't do it! But we'll need a sufficiently large dataset before you can objectively say that the added complexity has any impact.

You might consider including a weight pulled in from a custom gamma function that was added in #130. The gamma function gets a few constants (for example, `k` is the number of teams), but you can also pull in data from the scope at which you called `rate`. For example, try this:

```js
const model = 'thurstonMostellerFull'
const redTeam = [ rating(), rating() ]
const blueTeam = [ rating(), rating() ]
const shutoutFactor = Math.max(redScore,blueScore) / Math.max(Math.min(redScore,blueScore),Number.EPSILON)
const gamma = (_, k) => shutoutFactor / k
rate([redTeam, blueTeam], { model, gamma })
```

I would strongly encourage you to experiment, look at the impact scientifically, and allow for the null hypothesis. Ratings are imperfect heuristics. Intuitively we want to believe that more input will give us better output, but that might not be the case.

**Comment by philihp** [comment]
Closing, but feel free to reopen if you'd like to continue the thread
