### ISSUE TITLE
RFC: perhaps simpler rating function interface?

### ISSUE THREAD

**Issue by philihp** [philihp/openskill.js#231]
I'm curious if this might be a good idea? If this would be an easier interface, I'd love to hear from people. It could be added and overload the current behavior to do both.

Proposal: If you pass in an array of strings or numbers (things that aren't rating objects), then it treats those as like player IDs. For instance Alice and Betty are on a team. Cindy and Debby are on another team.:

```js
let ratings = {}
ratings = rate([['alice', 'betty'], ['cindy', 'debby']], { state: ratings })
// {
//   'alice': { mu: 26.964, sigma: 8.1776 },
//   'betty': { mu: 26.964, sigma: 8.1776 },
//   'cindy': { mu: 23.035, sigma: 8.1776 },
//   'debby': { mu: 23.035, sigma: 8.1776 }
// }
ratings = rate([['alice', 'cindy'], ['betty', 'debby']], { state: ratings })
// {
//   'alice': { mu: 28.888, sigma: 8.0257 },
//   'betty': { mu: 24.959, sigma: 8.0257 },
//   'cindy': { mu: 25.041, sigma: 8.0257 },
//   'debby': { mu: 21.112, sigma: 8.0257 }
// }
ratings = rate([['alice'],['betty']], { state: ratings })
// {
//   'alice': { mu: 30.663, sigma: 7.7960 },
//   'betty': { mu: 19.337, sigma: 7.7960 },
//   'cindy': { mu: 25.041, sigma: 8.0257 },
//   'debby': { mu: 21.112, sigma: 8.0257 }
// }
```

Thus instead of passing in rating objects, we'd pass in names of players or player IDs, and then we'd get back a new rating object. I believe strongly that `rate` should stay pure and not have the side effect of mutating the ratings contained in the object passed in.

I'm thinking this behavior would be triggered on if `typeof state === 'object'` (or if it were a dict/hash in other languages)

**Comment by philihp** [comment]
Just thinking out loud and hoping someone jumps in here before I go ahead and just do something that sucks... Another thought is currying the options ahead of rate (renaming to "ctx" in docs to hint that it's different now). I'd then make the default library import be the configurable thing (similar to how [fast-shuffle](https://github.com/philihp/fast-shuffle) does this), and using the default library import as a centrally configurable thing. So for instance if your system is configured with

```js
// ./ctx.js
export const ctx = {
  mu: 1000,
  state: {},
}
```

and then using the library looks like this.

```js
import openskill from 'openskill';
import { ctx } from './ctx';
const { rate, rating } = openskill(ctx);

rate([ ['alice','betty'], ['cindy','debby'] ]);
// {
//   'alice': { mu: 1083.3300783157224, sigma: 325.88529077215526 },
//   'betty': { mu: 1083.3300783157224, sigma: 325.88529077215526 },
//   'cindy': { mu: 916.6699216842776, sigma: 325.88529077215526 },
//   'debby': { mu: 916.6699216842776, sigma: 325.88529077215526 },
// }
```

and `state` inside the ctx would be replaced with a new hash, so the user can go lookup ratings without managing it
```js
import { ctx } from './ctx';
ctx.state.alice
// { mu: 1083.3300783157224, sigma: 325.88529077215526 }
```

**pro**: dooes more with less code.
**con**: might feel magic.

Gonna stew on this for a bit, kinda wanna do it though. Feels a little bit like React context, and that works well enough.

**Comment by daegontaven** [comment]
> and state inside the `ctx` would be replaced with a new hash, so the user can go lookup ratings without managing it
How would this work with storing the ratings in a database? Would we have to create a backend to openskill for databases as well? Wouldn't it be an extra value (hash) the users would have to store if there is no backend?

**Comment by philihp** [comment]
With this, Openskill wouldn't connect to any database, it would just manage holding ratings in memory. They'd still be available by directly accessing.

But now thinking about this... I think it's better the current way, being less opinionated about how the ratings are stored. Given the feedback I'm hearing from others, they want more features but the API is fine.
