### ISSUE TITLE
No @types/openskill on npm and types aren't included with the npm package?

### ISSUE THREAD

**Issue by maxweisel** [philihp/openskill.js#327]
Heyo,

I noticed the project is written in typescript, but the npm package doesn't seem to include types and there's no @types/openskill package. Is there a way to get the types without including openskill locally in project?

Max

**Comment by philihp** [comment]
Hmm, lemme check. I thought I released them (but I've never done a library in TS)

**Comment by philihp** [comment]
I pushed up an RC build, if you wanna check that out. I'll release that as 3.0.0 if everything seems fine after a month.

```
npm install --save openskill@next
```
or
```
npm install --save openskill@3.0.0-rc0
```

**Comment by philihp** [comment]
Deployed with 3.0.0
