### ISSUE TITLE
Help explaining ties

### ISSUE THREAD

**Issue by jderrough** [philihp/openskill.js#332]
Hi!

Could someone please help me understand how ties work given the examples below?

```
const result = rate(
  [[rating()], [rating()], [rating()], [rating()]],
  {
    rank: [1, 2, 3, 2],
  }
)

//  result, ordinal: [
//    3.0056026990343057, //  1st
//    0.15179388828942209, //  2nd
//    -1.7115960929604057, //  3rd
//    0.15179388828942209 //  2nd
//  ]
```

So far so good, but...

```
const result = rate(
  [[rating()], [rating()], [rating()], [rating()], [rating()]],
  {
    rank: [1, 2, 3, 2, 4],
  }
)

//  result, ordinal: [
//    2.794996035203244, //  1st
//    0.44622977732347024, //  ranked 2nd but skill is 3rd
//    0.649325864695502, //  ranked 3rd but skill is 2nd
//    0.44622977732347024, //  ranked 2nd but skill is 3rd
//    -2.6840074686378337 //  4th
//  ]
```

It gets "worse"...

```
const result = rate(
  [[rating()], [rating()], [rating()], [rating()], [rating()], [rating()], [rating()], [rating()]],
  {
    rank: [1, 2, 3, 2, 4, 5, 6, 7],
  }
)

//  result, ordinal: [
//    2.3490991742487033, //  1st
//    0.7035551798587676, //  ranked 2nd but skill is 4th
//    1.5576843491759007, //  ranked 3rd but skill is 2nd
//    0.7035551798587676, //  ranked 2nd but skill is 4th
//    0.973568140809558, //  ranked 4th but skill is 3rd
//    0.18397380061958657, //  5th
//    -1.0333401668557407, //  6th
//    -3.668571550329389 //  7th
//  ]
```

Thanks!

**Comment by daegontaven** [comment]
@jderrough  Let's start with a simple case of what we know should work. Which is that ranks passed in will reflect the values of ordinals:

![image](https://user-images.githubusercontent.com/8206808/200142269-100e632a-3d57-4864-abcc-7c291f79c8fa.png)

Let's visualize the plots of each distribution overlapped on each other:

![image](https://user-images.githubusercontent.com/8206808/200142381-d0b321a3-7bee-4eeb-8b5c-81e6b5746ae5.png)

**Comment by philihp** [comment]
Well said! That helps a lot to visualize the curve to see that it has a higher peak, which may not be intuitive by just looking at &mu; and &sigma;. I suppose that can be interpreted as saying... "while you may have lost, we are more confident that your actual rating is somewhere around here".
