### ISSUE TITLE
Predict Ranks

### ISSUE THREAD

**Issue by vivekjoshy** [philihp/openskill.js#347]
I've implemented a [`predict_rank`](https://openskill.me/en/latest/manual.html#predicting-ranks) feature that well, predicts the rank order of teams given a set of teams. Would be amazing if it got implemented here.

Relevant Pull Request: https://github.com/OpenDebates/openskill.py/pull/74

**Comment by philihp** [comment]
Cool! Sure, I'm down 👍 

(to anyone reading this: if you're interested in doing it, and this issue is still open, that means i haven't found the time to do it yet and i'd welcome a PR contribution)
