### ISSUE TITLE
predict_win methods appears to give incorrect values in the 2 player case

### ISSUE THREAD

**Issue by DJMelksham** [philihp/openskill.js#453]
I've been experimenting with the prediction function and I would expect to get equal probabilities for two player teams 1 member each both with the same ratings.  This isn't what I'm currently seeing.

i.e. PlackettLuce with two players in two teams, both with default ratings:
```
from openskill.models import PlackettLuce
model = PlackettLuce()
a = model.rating()
b = model.rating()
model3.predict_win([[a], [b]])
```

[0.38146287993364575, 0.6185371200663543]

Additionally, when I input teams with differing ratings, the order in which I put them appears to effect the probability estimates that I see returned :(?

```
from openskill.models import PlackettLuce
model = PlackettLuce()
r = model.rating
[[a, b], [x, y]] = [[r(), r()], [r(), r()]]
[[a, b], [x, y]] = model.rate([[a, b], [x, y]])
[[a, x], [b, y]] = model.rate([[a, x], [b, y]])
model.predict_win([[a], [b]])
```
[0.49602898384231453, 0.5039710161576855]
`model.predict_win([[b], [a]])`
[0.27041217584012034, 0.7295878241598797]

Happy to be told I'm doing something silly...

**Comment by vivekjoshy** [comment]
Please see https://github.com/OpenDebates/openskill.py/issues/53

**Comment by vivekjoshy** [comment]
v5.0.1 with Bugfix Released 🥳
