### ISSUE TITLE
Self vs Self is not always a 100% draw

### ISSUE THREAD

**Issue by miltoncandelero** [philihp/openskill.js#477]
I am rewriting this lib in a different language and while writing tests I found that not all mirror matches return a probability of 1 in the draw

a mirror match of player `a1` ends up with a non 1 draw chance

![image](https://github.com/philihp/openskill.js/assets/15253010/6dc4ed30-a4cd-4a10-970d-c10005688465)

https://github.com/philihp/openskill.js/blob/224dd538e0003b13ef315d89e3f53fff0d5217a1/src/__tests__/predict-draw.test.ts#L25-L28

**Comment by vivekjoshy** [comment]
Draw probabilities are never close to 1 even for mirror matches. The uncertainty (`sigma`) for each player in team add up to ensure that. This is not a bug.

**Comment by miltoncandelero** [comment]
Thanks for the confirmation!

I was just confused by the name of the test 😅

**Comment by vivekjoshy** [comment]
That particular test is comparing `b1` with itself. But it's got a very low `sigma` value. The lower the value, the higher the chance of a draw with itself.

**Comment by philihp** [comment]
Feel free to open a PR if you'd like to change the name of the test to something better :)
