### ISSUE TITLE
predictDraw gives wrong result

### ISSUE THREAD

**Issue by jauggy** [philihp/openskill.js#599]
```
        const teams = [
            [
                {
                    "mu": 25,
                    "sigma": 1
                },
                {
                    "mu": 25,
                    "sigma": 1
                }
            ],
            [
                {
                    "mu": 25,
                    "sigma": 1
                },
                {
                    "mu": 25,
                    "sigma": 1
                }
            ]
        ]

        const result = predictDraw(teams)
        console.log(result);

```

This gives a result of 1.22
  openskill version "3.1.0"

**Comment by vivekjoshy** [comment]
Relevant Python Version:

```py
>>> from openskill.models import PlackettLuce
>>> model = PlackettLuce()
>>> r = model.rating
>>> t1 = [r(25, 1), r(25, 1)]
>>> t2 = [r(25, 1), r(25, 1)]
>>> model.predict_draw([t1, t2])
0.6608263448857606
```

**Comment by vivekjoshy** [comment]
To add to this issue, both functions (`predict_win` and `predict_draw`) were bugfixed a while ago in the python version, I may have forgotten to let @philihp know about the changes. The issue stems from the double squaring of the the sigma values. The sigma value is already squared, so it shouldn't be squared again.

https://github.com/philihp/openskill.js/blob/9e35b0cafc7b33ac24560ea0d1a6d983c85d53f9/src/predict-draw.ts#L26

https://github.com/philihp/openskill.js/blob/9e35b0cafc7b33ac24560ea0d1a6d983c85d53f9/src/predict-win.ts#L18

Python Variant:

https://github.com/vivekjoshy/openskill.py/blob/cc684f1e06231d75a24f0183cf0bcb21e44cae89/openskill/models/weng_lin/plackett_luce.py#L757

https://github.com/vivekjoshy/openskill.py/blob/cc684f1e06231d75a24f0183cf0bcb21e44cae89/openskill/models/weng_lin/plackett_luce.py#L816
