### ISSUE TITLE
Is there a way to use openskill from ts code?

### ISSUE THREAD

**Issue by br0x** [philihp/openskill.js#627]
I keep getting this when trying to call rate():
`    TypeError: (0 , import_sort_unwind.default) is not a function or its return value is not iterable

      33 |
      34 |     console.log('teamRatings: ', teamRatings);
    > 35 |     const newTeamRatings = rate(teamRatings);
         |                                ^
      36 |     console.log('newTeamRatings: ', newTeamRatings);
      37 |
      38 |     newTeamRatings.forEach((team, index) => {

      at unwind (node_modules/openskill/src/rate.ts:28:33)
      at OpenSkillRatingSystem.updateRatings (src/ratings/OpenSkillRatingSystem.ts:35:32)
 `
 
 Here is minimal code example:
import { rate, rating } from 'openskill';
import { Team } from 'openskill/dist/types';

const team1: Team = [rating()];
const team2: Team = [rating()];
const teamRatings = [team1, team2];
console.log('teamRatings: ', teamRatings);

const newTeamRatings = rate(teamRatings);
console.log('newTeamRatings: ', newTeamRatings);

**Comment by preeefix** [comment]
I'm getting this without using TS. It looks like because `sort-unwind` was updated with cjs build components and it broke openskill, somehow...

**Comment by philihp** [comment]
Lemme take a look, apologies.

**Comment by philihp** [comment]
yeah sorry this really should work. i don't know why right now and i'm traveling and doing an npm install is just spinning forever. i hope to get to this in a few days, but if you can figure it out please feel free to open a PR to either repo.

alternatively, version 3 should still work. i sincerely apologize, these ESM/CJS problems are hella frustrating.

**Comment by jlcarvalho** [comment]
I'm having the same issue with `tsc` but not with `vitest`, so my test suite works, but my production builds don't.

Unfortunately, I need the `predictWin` fix introduced by v4.0.0.

**Comment by jlcarvalho** [comment]
Maybe using something like this could help: https://github.com/knightedcodemonkey/duel

**Comment by preeefix** [comment]
I'm able to use 4.0.1 successfully as it's the last commit since the upgrade to cjs for `sort-unwind`.

**Comment by philihp** [comment]
This should be fixed in 4.0.3 🙏 

I'm 95% sure it has something to do with CJS and default exports. I think turning `esModuleInterop` on in some tsconfig might have fixed it (but whose tsconfig? 🤷‍♂️ ), but honestly it was easier just to give the default export of sort-unwind a named export instead. Thank you for that codesandbox link! It helped a lot in figuring this out.

Please let me know if 4.0.3 does the trick; it seems to be good at https://codesandbox.io/p/sandbox/openskill-error-forked-7r94kw

**Comment by jlcarvalho** [comment]
Seems like your codesandbox is private, but I'm going to do some tests with v4.0.3 next week.

**Comment by philihp** [comment]
should be public now 😅

**Comment by philihp** [comment]
Sounds like everyone has this is resolved with how they're using the library. Please reopen if there are any complications!
